name: Tests
on: [push]
jobs:
  test:
    name: Run
    strategy:
      matrix:
        blender:
          - version: '2.83.20'
            python: '3.7'
          - version: '3.0.1'
            python: '3.9'
          - version: '3.1.2'
            python: '3.10'
            coverage: 'coverage'
    runs-on: ubuntu-latest
    env:
      BLENDER_PATH: .blender
      BLENDER_VERSION: ${{ matrix.blender.version }}
      BLENDER_PYTHON_VERSION: ${{ matrix.blender.python }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.BLENDER_PATH }}
          key: blender:${{ env.BLENDER_VERSION }}:cov632
      - name: Prepare
        run: ./tests/ci-prepare.sh
      - name: Test
        run: ./$BLENDER_PATH/blender --factory-startup -noaudio -b --python-exit-code 1 --python tests/runner.py
      - name: Coverage
        if: ${{ matrix.blender.coverage == 'coverage' }}
        run: bash <(curl -s https://codecov.io/bash)
